# Use the README file as a reference to customize settings.

AdminOperationLog:
  fields:
    default: id, parent_type, parent_id, admin_user_id, operation
    form: admin_user_id, operation
  relationships: 
  application: Application
  order_by: -id
