# Use the README file as a reference to customize settings.

Author:
  fields:
    default: name, name_kana, publiced
    list: id, name, name_kana, publiced
    form: name, name_kana, publiced
    options:
      booleans:
        publiced: ["活動中", "活動停止"]
  order_by: -id
  search: name, name_kana
  filters: publiced
  relationships: sites
  application: Application
