# Use the README file as a reference to customize settings.

Author:
  fields:
    default: name, name_kana
    form: name, name_kana
    order_by: -name
    search: =name
  relationships: sites
  application: Application
