# Use the README file as a reference to customize settings.

Site:
  fields:
    default: title, href, author_id, media_id, status, publiced_at, closed_at
    form: title, href, author_id, media_id, status, publiced_at, closed_at
    list: id, title, href, author_id, media_id, status, publiced_at, closed_at
    options:
      selectors: media_id, status
  relationships: 
  application: Application
  filters: status
  search: title
  order_by: -id
