# Use the README file as a reference to customize settings.

Site:
  fields:
    default: title, href, author_id, media_id, status, publiced_at, closed_at
    form: author_id, title, href, media_id, status, publiced_at, closed_at, memo
    list: author_id, id, title, href, media_id, status, publiced_at, closed_at
    options:
      selectors: media_id, status
  relationships: 
  application: Application
  filters: status
  search: title
  order_by: -id
