# Use the README file as a reference to customize settings.

Site:
  fields:
    default: title, href, author_id, media_id, publiced_at, closed_at
    form: title, href, author_id, media_id, publiced_at, closed_at
    options:
      selectors: media_id
  relationships: 
  application: Application
