development:
  adapter: mysql2
  database: dirital_root_hub_dev
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: dirital_root_hub_test
  username: root
  password: root
  host: localhost

staging:
  adapter: mysql2
  database: dirital_root_hub_staging
  username: root
  host: localhost

production:
  adapter: mysql2
  database: dirital_root_hub
  username: cook24
  host: localhost

